In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
df=df.drop('Gender',axis=1)

In [ ]:
df.sample(5)

      User ID  Age  EstimatedSalary  Purchased
334  15814553   57            60000          1
185  15814816   31            66000          0
34   15724858   27            90000          0
40   15764419   27            17000          0
370  15611430   60            46000          1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.drop('Purchased',axis=1),df['Purchased'],test_size=0.3,random_state=0)

In [ ]:
X_train

      User ID  Age  EstimatedSalary
92   15809823   26            15000
223  15593715   60           102000
234  15619407   38           112000
232  15813113   40           107000
377  15800215   42            53000
..        ...  ...              ...
323  15619465   48            30000
192  15779581   29            43000
117  15591433   36            52000
47   15776348   27            54000
172  15794661   26           118000

[280 rows x 3 columns]

In [ ]:
y_train

92     0
223    1
234    0
232    1
377    0
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 280, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()
scaler.fit(X_train)
x_train_scale=scaler.transform(X_train)
x_test_scale=scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr=LogisticRegression()

lr_scale=LogisticRegression()

In [ ]:
lr.fit(X_train,y_train)

lr_scale.fit(x_train_scale,y_train)

LogisticRegression()

In [ ]:
y_pred=lr.predict(X_test)

In [ ]:
y_scale_predt=lr_scale.predict(x_test_scale)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print(accuracy_score(y_test,y_pred))

0.8666666666666667

In [ ]:
print(accuracy_score(y_test,y_scale_predt))

0.8833333333333333